blueprint:
  name: Aula inteligente 1 - Multi dispositivos
  description: "Plugin diseñado para la automatización integral de salones de clase. Soporta múltiples luces y termostatos."
  domain: automation
  input:
    motion_sensors:
      name: Sensores de Movimiento
      description: "Sensores de movimiento para detectar la presencia en el aula. Pueden ser binary_sensor o switch."
      selector:
        entity:
          domain:
            - binary_sensor
            - switch
          multiple: true

    opening_sensor:
      name: Sensor de puerta 
      description: "Un sensor de puerta para detectar eventos de apertura/cierre."
      default: ""
      selector:
        entity:
          domain: binary_sensor
          device_class: door

    target_lights:
      name: Iluminación del Aula
      description: "Luces y switches que se controlarán automáticamente. Puedes seleccionar múltiples."
      selector:
        entity:
          domain:
            - light
            - switch
          multiple: true

    target_climates:
      name: Termostatos (Opcional)
      description: "Termostatos del aula. Puedes seleccionar múltiples equipos de clima."
      default: []
      selector:
        entity:
          domain: climate
        multiple: true

    classroom_status:
      name: Estado del Aula (Helper)
      description: "Helper input_select que mostrará LIBRE u OCUPADA."
      selector:
        entity:
          domain: input_select

    target_temperature:
      name: Temperatura Objetivo
      description: "Temperatura deseada cuando hay presencia en el aula."
      default: 22
      selector:
        number:
          min: 20
          max: 26
          unit_of_measurement: "°C"
          mode: slider

    off_delay:
      name: Tiempo de apagado
      description: "Tiempo de espera antes de considerar el aula libre tras no detectar presencia."
      default: 300
      selector:
        number:
          min: 60
          max: 1800
          unit_of_measurement: seconds
          mode: slider
          step: 30

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensors
    id: "motion_detected"

condition: []

action:
  - variables:
      motion_sensors_list: !input motion_sensors
      opening_sensor_entity: !input opening_sensor
      climate_list: !input target_climates
      lights_list: !input target_lights
      status_entity: !input classroom_status

  - choose:

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.to_state.state in ['on', 'detected'] }}
        sequence:

          - service: input_select.select_option
            target:
              entity_id: !input classroom_status
            data:
              option: "OCUPADA"


          - service: homeassistant.turn_on
            data:
              entity_id: !input target_lights


          - service: climate.set_temperature
            data:
              entity_id: !input target_climates
              temperature: !input target_temperature
              hvac_mode: "cool"

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.to_state.state in ['off', 'clear'] }}
        sequence:

          - delay:
              seconds: !input off_delay


          - condition: template
            value_template: >-
              {%- set motion_entities = motion_sensors_list -%}
              {%- if motion_entities is string -%}
                {%- set motion_list = [motion_entities] -%}
              {%- else -%}
                {%- set motion_list = motion_entities -%}
              {%- endif -%}
              {%- set all_clear = namespace(value=true) -%}
              {%- for sensor in motion_list -%}
                {%- if states(sensor) not in ['off', 'clear', 'unavailable'] -%}
                  {%- set all_clear.value = false -%}
                {%- endif -%}
              {%- endfor -%}
              {{ all_clear.value }}


          - service: input_select.select_option
            target:
              entity_id: !input classroom_status
            data:
              option: "LIBRE"


          - service: homeassistant.turn_off
            data:
              entity_id: !input target_lights


          - service: climate.set_hvac_mode
            data:
              entity_id: !input target_climates
              hvac_mode: "off"