blueprint:
  name: Aula inteligente 1
  description: "Plugin diseñado para la automatización integral de salones de clase. Optimiza la gestión y operación del entorno educativo."
  domain: automation
  input:
    motion_sensor_battery:
      name: Sensor de Movimiento (Batería)
      description: "Un sensor de movimiento (binary_sensor) para detectar la presencia en el aula."
      default: ""
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    motion_sensor_electrical:
      name: Sensor de Movimiento (Eléctrico)
      description: "Un interruptor que simula el sensor de movimiento eléctrico."
      default: ""
      selector:
        entity:
          domain: switch

    target_light:
      name: Iluminación del Aula
      description: "Luz o grupo de luces que se controlarán automáticamente."
      selector:
        entity:
          domain: light

    target_climate:
      name: Termostato
      description: "Un termostato para ajustar la temperatura del aula."
      default: ""
      selector:
        target:
          entity:
            domain: climate

    classroom_status:
      name: Estado del Aula (Helper)
      description: "Helper input_select o input_text que mostrará LIBRE u OCUPADA."
      selector:
        entity:
          domain: input_select

    target_temperature:
      name: Temperatura Objetivo
      description: "Temperatura deseada cuando hay presencia en el aula."
      default: 22
      selector:
        number:
          min: 20
          max: 26
          unit_of_measurement: "°C"
          mode: slider

    off_delay:
      name: Tiempo de apagado
      description: "Tiempo de espera antes de considerar el aula libre tras no detectar presencia."
      default: 300
      selector:
        number:
          min: 60
          max: 1800
          unit_of_measurement: seconds
          mode: slider
          step: 30

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensor_battery
    id: "battery_sensor"
    enabled: "{{ motion_sensor_battery != '' }}"
  - platform: state
    entity_id: !input motion_sensor_electrical
    id: "electrical_sensor"
    enabled: "{{ motion_sensor_electrical != '' }}"

condition: []

actions:
  - variables:
      motion_battery: !input motion_sensor_battery
      motion_electrical: !input motion_sensor_electrical
      climate_entity: !input target_climate
      status_entity: !input classroom_status

  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ status_entity.startswith('input_select.') }}"
                sequence:
                  - service: input_select.set_option
                    target:
                      entity_id: !input classroom_status
                    data: "OCUPADA"

          - service: light.turn_on
            target:
              entity_id: !input target_light
          - service: climate.set_hvac_mode
            target: !input target_climate
            data:
              hvac_mode: "cool"

      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state in ['off', 'clear'] }}"

        sequence:
          - delay:
              seconds: !input off_delay

          - condition: template
            value_template: >-
              {%- set battery_clear = motion_battery == '' or states(motion_battery) in ['off', 'clear'] -%}
              {%- set electrical_clear = motion_electrical == '' or states(motion_electrical) in ['off', 'clear'] -%}
              {{ battery_clear and electrical_clear }}

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ status_entity.startswith('input_select.') }}"
                sequence:
                  - service: input_select.set_option
                    target:
                      entity_id: !input classroom_status
                    data: "LIBRE"

          - service: light.turn_off
            target:
              entity_id: !input target_light
          - service: climate.set_hvac_mode
            target: !input target_climate
            data:
              hvac_mode: "off"
